= Model Context Protocol Sever for JDBC
:mpcalias: mcp-server-jdbc@quarkusio

This Model Context Protocol(MCP) server enables Large Language Models (LLMs) to inspect, query, create and modify database content given just a Java Database Connectivity (JDBC) url.

Supported databases include PostgresSQL, Oracle, MariaDB, Sqlite and <<jdbc_variants,many more>>.

== General Usage 

1. Install https://www.jbang.dev/download/[jbang]
2. Configure your MCP Client to run the server (see <<claude_desktop_config>> below)

Below are examples of command lines to use for configuring the server.

Start with an empty database (in-memory h2 database):

[source,shell,subs="attributes"]
----
jbang {mpcalias}
----

A live database (any common JDBC compatible database):

[source,shell,subs="attributes"]
----
jbang {mpcalias} [jdbc_url]
----

For example, to connect to a already running Oracle database:

[source,shell,subs="attributes"]
----
jbang {mpcalias} jdbc:oracle:thin:@localhost:1521:orcl
----

You can also specify a user and password separately, here for a PostgreSQL database:

[source,shell,subs="attributes"]
----
jbang {mpcalias} jdbc:postgresql://localhost:5432/sakila -u sakila -p p_ssW0rd
----

== Downloadable databases

JBang can download files from the web and feed them directly to databases like h2 and sqlite.

That is done using the %{url} syntax.

Following is an example of how to connect to a Chinook database in SQLite, downloading the `Chinook_Sqlite.sqlite` file from github.

[source,shell,subs="attributes"]
----
jbang {mpcalias} jdbc:sqlite:%{https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite}
----

There are interesting examples of sample data available online you can use to explore data.

Below are a non-exhaustive list of databases and example JDBC urls that are known to work with this server as-is (no additional configuration required).

=== Example databases 

Chinook::

Sample music store data including artists, albums, tracks, invoices etc.
[source]
----
jdbc:sqlite:%{https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite}
----

Northwind:: 

Classic Microsoft sample database with customers, orders, products etc.

[source]
----
jdbc:sqlite:%{https://github.com/jpwhite3/northwind-SQLite3/raw/refs/heads/main/dist/northwind.db}
----

Netflix Movies:: 

Sample movie data based on Netflix catalog
[source]
----
jdbc:sqlite:%{https://github.com/lerocha/netflixdb/releases/download/v1.0.0/netflixdb.sqlite}
----

== Supported JDBC variants [[jdbc_variants]]

.JDBC variants
|===
|Database|Dependency

|https://mariadb.com/kb/en/mariadb-connector-j/[MariaDB]
|org.mariadb.jdbc:mariadb-java-client:RELEASE

|https://dev.mysql.com/doc/connector-j/8.0/en/[MySQL]
|mysql:mysql-connector-java:RELEASE,

|https://jdbc.postgresql.org/documentation/head/connect.html[PostgreSQL]
|org.postgresql:postgresql:RELEASE,

|https://docs.oracle.com/en/database/oracle/oracle-database/19/jjdbc/JDBC-driver-connection-url-syntax.html[Oracle]
|com.oracle.database.jdbc:ojdbc10:RELEASE

|https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15[SQL Server]
|com.microsoft.sqlserver:mssql-jdbc:RELEASE

|https://help.sap.com/viewer/0eec0d68141541d1b07893a39944924e/2.0.02/en-US/109397c2206a4ab2a5386d494f4cf75e.html[SAP DB]
|com.sapcloud.db.jdbc:ngdbc:RELEASE

|https://www.ibm.com/docs/en/informix-servers/14.10?topic=SSGU8G_14.1.0/com.ibm.jdbc_pg.doc/ids_jdbc_501.htm[Informix]
|com.ibm.informix:jdbc:RELEASE

|https://www.firebirdsql.org/file/documentation/drivers_documentation/java/3.0.7/firebird-classic-server.html[Firebird]
|org.firebirdsql.jdbc:jaybird:RELEASE

|https://hsqldb.org/doc/2.0/guide/dbproperties-chapt.html[hsqldb]
|org.hsqldb:hsqldb:RELEASE

|https://www.h2database.com/html/features.html#database_url[h2]
|com.h2database:h2:RELEASE

|https://db.apache.org/derby/docs/10.8/devguide/cdevdvlp17453.html[Apache Derby]
|org.apache.derby:derby:RELEASE

|SQLite
|org.xerial:sqlite-jdbc:RELEASE
|===

== Components

Below are the MCP components provided by this server.

=== Tools 

* *read_query* - do a SELECT query on the database
* *write_query* - do a INSERT, UPDATE, DELETE query on the database
* *create_table* - create a table in the database
* *list_tables* - list all tables in the database
* *describe_table* - describe a table

=== Prompts

* *jdbc_demo* - example prompt to get started exploring the server (similar to the one in sqllite MCP)

== Claude Desktop Config and https://github.com/chrishayuk/mcp-cli[mcp-cli] [[claude_desktop_config]]


Add this to your `claude_desktop.json` or `server_config.json` file:

[source,json]
----
{
  "mcpServers": {
    "jdbc": {
      "command": "jbang",
      "args": [
        "--quiet",
        "{mpcalias}",
        "[jdbc_url]"
      ]
    }
  }
}
----

=== Troubleshooting

jbang not found::
* Make sure you have `jbang` installed and available in your PATH
* Alternatively, use full path to jbang executable (e.g. `/Users/username/.jbang/jbang`)

Get more logging::

To get more detailed logging you can add the following parameters to the jbang command line:

[source,shell]
----
-Dquarkus.log.file.enable=true -Dquarkus.log.file.path=${user.home}/mcp-server-jdbc.log
----

Example:

[source,shell,subs="attributes"] 
----
jbang -Dquarkus.log.file.enable=true -Dquarkus.log.file.path=${user.home}/mcp-server-jdbc.log {mpcalias} jdbc:h2:mem:testdb
----

=== How was this made ?

The MCP server uses Quarkus, the Supersonic Subatomic Java Framework and its Model Context Protocol support.

If you want to learn more about Quarkus MCP Server support, please see this https://quarkus.io/blog/mcp-server/[blog post] 
and the Quarkus MCP Server https://docs.quarkiverse.io/quarkus-mcp-server/dev/[extension documentation].

To launch the server and handle the magic setup of JDBC urls it uses https://jbang.dev/[jbang] to
setup Java and run the .jar as transparent as possible. Very similar to how `uvx`, `pipx`, `npmx` and others works; just for Java.

